#!/usr/bin/env node

import { rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { readExpandedConvexFixture } from "./cohort-fixture.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.resolve(__dirname, "fixtures/cohort-sample-data.json");
const seedModuleName = "cohortSampleSeed.ts";

function parseArgs(argv) {
  const options = {
    target: process.cwd(),
    install: false,
    run: false,
    clean: false,
    yes: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--target") {
      options.target = path.resolve(argv[index + 1]);
      index += 1;
    } else if (arg === "--install") {
      options.install = true;
    } else if (arg === "--run") {
      options.install = true;
      options.run = true;
    } else if (arg === "--clean") {
      options.clean = true;
    } else if (arg === "--yes") {
      options.yes = true;
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown option: ${arg}`);
    }
  }

  return options;
}

function printHelp() {
  console.log(`Usage:
  npm run seed:convex:plan
  npm run seed:convex
  npm run seed:convex:clean

Default mode prints the seed plan only.

The --run mode writes a temporary convex/${seedModuleName}, pushes Convex
functions once, runs cohortSampleSeed:seed, prints cohortSampleSeed:summary,
and leaves the temporary module for inspection. Clean it with seed:convex:clean.
`);
}

function buildSeedModule(fixture) {
  const fixtureJson = JSON.stringify(fixture, null, 2);

  return `// Generated by scripts/seed-convex.mjs.
// Temporary cohort seed module. Remove with npm run seed:convex:clean.

import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";

const fixture = ${fixtureJson} as const;

const seededUserIds: Set<string> = new Set(fixture.users.map((user) => user.userId));

function documentKey(document: { seedKey?: string; userId: string; title: string }) {
  return document.seedKey ?? document.userId + ":" + document.title;
}

async function deleteSeededRows(ctx: MutationCtx) {
  for (const agent of await ctx.db.query("squadAgents").collect()) {
    if (seededUserIds.has(agent.userId)) await ctx.db.delete(agent._id);
  }

  for (const file of await ctx.db.query("files").collect()) {
    if (seededUserIds.has(file.userId)) await ctx.db.delete(file._id);
  }

  for (const message of await ctx.db.query("coworkerMessages").collect()) {
    if (seededUserIds.has(message.userId)) await ctx.db.delete(message._id);
  }

  for (const setting of await ctx.db.query("aiSettings").collect()) {
    if (seededUserIds.has(setting.userId)) await ctx.db.delete(setting._id);
  }

  for (const storage of await ctx.db.query("userStorage").collect()) {
    if (seededUserIds.has(storage.userId)) await ctx.db.delete(storage._id);
  }

  for (const document of await ctx.db.query("documents").collect()) {
    if (seededUserIds.has(document.userId)) await ctx.db.delete(document._id);
  }
}

export const seed = mutation({
  args: {
    reset: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    if (args.reset ?? true) {
      await deleteSeededRows(ctx);
    }

    const now = Date.now();
    const documentIdsByKey: Record<string, Id<"documents">> = {};

    for (const document of fixture.documents) {
      documentIdsByKey[documentKey(document)] = await ctx.db.insert("documents", {
        title: document.title,
        userId: document.userId,
        isArchived: document.isArchived,
        isPublished: document.isPublished,
        content: document.content,
        icon: "icon" in document ? document.icon : undefined,
      });
    }

    for (const user of fixture.users) {
      await ctx.db.insert("aiSettings", {
        userId: user.userId,
        activeProvider: user.aiProvider,
        activeModel: user.aiModel,
        createdAt: now,
        updatedAt: now,
      });

      await ctx.db.insert("userStorage", {
        userId: user.userId,
        bytesUsed: user.bytesUsed,
        updatedAt: now,
      });
    }

    for (const file of fixture.files) {
      const fileRecord = file as {
        documentSeedKey?: string;
        documentTitle?: string;
        userId: string;
      };
      const documentId = fileRecord.documentSeedKey
        ? documentIdsByKey[fileRecord.documentSeedKey]
        : fileRecord.documentTitle
          ? documentIdsByKey[fileRecord.userId + ":" + fileRecord.documentTitle]
          : undefined;

      await ctx.db.insert("files", {
        name: file.name,
        type: file.type,
        url: file.url,
        userId: file.userId,
        size: file.size,
        documentId,
        documentIds: documentId ? [documentId] : undefined,
        checksum: file.checksum,
        createdAt: now,
      });
    }

    for (const bucket of fixture.coworkerMessages) {
      for (let index = 0; index < bucket.count; index += 1) {
        const createdAt = now - (bucket.count - index) * 60_000;
        await ctx.db.insert("coworkerMessages", {
          userId: bucket.userId,
          role: bucket.role,
          content: "Synthetic cohort sample message " + String(index + 1),
          createdAt,
        });
      }
    }

    for (const agent of fixture.squadAgents) {
      let instructionsDocId = documentIdsByKey[agent.userId + ":" + agent.instructionsDocSeedTitle];
      if (!instructionsDocId) {
        instructionsDocId = await ctx.db.insert("documents", {
          title: agent.instructionsDocSeedTitle,
          userId: agent.userId,
          isArchived: false,
          isPublished: false,
          content: "Synthetic instructions document for the cohort sample agent.",
          icon: agent.icon,
        });
      }

      await ctx.db.insert("squadAgents", {
        userId: agent.userId,
        name: agent.name,
        description: agent.description,
        icon: agent.icon,
        instructionsDocId,
        createdAt: now,
        updatedAt: now,
      });
    }

    return await summarizeRows(ctx);
  },
});

export const summary = query({
  args: {},
  handler: async (ctx) => {
    return await summarizeRows(ctx);
  },
});

async function summarizeRows(ctx: QueryCtx) {
  const documents = (await ctx.db.query("documents").collect()).filter((row) =>
    seededUserIds.has(row.userId),
  );
  const messages = (await ctx.db.query("coworkerMessages").collect()).filter((row) =>
    seededUserIds.has(row.userId),
  );
  const files = (await ctx.db.query("files").collect()).filter((row) =>
    seededUserIds.has(row.userId),
  );
  const squadAgents = (await ctx.db.query("squadAgents").collect()).filter((row) =>
    seededUserIds.has(row.userId),
  );

  return {
    users: fixture.users.length,
    documents: documents.length,
    publishedDocuments: documents.filter((row) => row.isPublished).length,
    coworkerMessages: messages.length,
    files: files.length,
    squadAgents: squadAgents.length,
    chatToPublish: fixture.users.map((user) => ({
      userId: user.userId,
      persona: user.persona,
      messages: messages.filter((row) => row.userId === user.userId).length,
      publishedDocuments: documents.filter(
        (row) => row.userId === user.userId && row.isPublished,
      ).length,
    })),
  };
}
`;
}

function runCommand(command, args, cwd) {
  const result = spawnSync(command, args, {
    cwd,
    stdio: "inherit",
    shell: false,
  });

  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed`);
  }
}

function assertWriteAllowed(options, action) {
  if (!options.yes) {
    throw new Error(`${action} requires --yes`);
  }
}

async function installSeedModule(targetRoot, fixture) {
  const seedModulePath = path.resolve(targetRoot, "convex", seedModuleName);
  await writeFile(seedModulePath, buildSeedModule(fixture), "utf8");
  return seedModulePath;
}

async function cleanSeedModule(targetRoot) {
  const seedModulePath = path.resolve(targetRoot, "convex", seedModuleName);
  await rm(seedModulePath, { force: true });
  return seedModulePath;
}

function printPlan(fixture) {
  console.log("# Convex seed plan");
  console.log(`Users: ${fixture.users.length}`);
  console.log(`Documents: ${fixture.documents.length}`);
  console.log(`Files: ${fixture.files.length}`);
  console.log(`Coworker message user buckets: ${fixture.coworkerMessages.length}`);
  console.log(`Squad agents: ${fixture.squadAgents.length}`);
  console.log("");
  console.log("Insights this sample supports:");
  for (const insight of fixture.insights) {
    console.log(`- ${insight.name}: ${insight.studentQuestion}`);
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const fixture = await readExpandedConvexFixture(fixturePath);

  if (options.clean) {
    assertWriteAllowed(options, "Cleaning the Convex seed module");
    const removedPath = await cleanSeedModule(options.target);
    console.log(`Removed ${removedPath}`);
    return;
  }

  printPlan(fixture);

  if (!options.install) {
    console.log("");
    console.log("Dry run only. Run npm run seed:convex to seed your connected Convex deployment.");
    return;
  }

  assertWriteAllowed(options, "Installing the Convex seed module");
  const seedModulePath = await installSeedModule(options.target, fixture);
  console.log("");
  console.log(`Installed ${seedModulePath}`);

  if (!options.run) return;

  console.log("");
  console.log("Pushing Convex functions and running seed mutation...");
  runCommand("npx", ["convex", "dev", "--once"], options.target);
  runCommand("npx", ["convex", "run", "cohortSampleSeed:seed", '{"reset":true}'], options.target);
  runCommand("npx", ["convex", "run", "cohortSampleSeed:summary"], options.target);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
